spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.105:3306/ads?setUnicode=true&characterEncoding=utf8&useAffectedRows=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123
#    url: jdbc:mysql://127.0.0.1:3306/ads?setUnicode=true&characterEncoding=utf8&useAffectedRows=true&useSSL=false&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 1234

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true
    #该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性

logging:
  pattern:
    #设置日志等级
    level: DEBUG
    #设置输出日期格式
    dateformat: yyyy年MM月dd日HH:mm:ss
  #把日志输出到log/mylog.log文件中，这是相对路径，也可以用绝对路径
  file: log/mylog.log

server:
  port: 8088
